### ISSUE TITLE
download not working

### ISSUE THREAD

**Issue by stevebutton** [willymaps/scrollydrive#2]
thanks for creating this -however when I download does not function.
I have no problem with the original Mapbox files (which led me to your addition), but can't get yours to work (I've added a Mapbox key). Get no result from either your geojson files or any new ones I create.
In addition your demo file (to me) is blank -
any idea what might be going on?
thanks in advance

**Comment by nonoumasy** [comment]
the same here. I downloaded and added my API token and I kept the default parkstroll.geojson but when I view the index.html, all it shows is the default map(it showing Europe for me), but it's not showing the route. I'm thinking the geojson is not connected. The config.js seems to be connected since when I change the map style there, it changes on the index.html as well.

**Comment by willymaps** [comment]
Sorry for the late reply Steve and glad it's being echoed here. I just tested a fresh download to my computer and it seems to work. Not sure if you're running a local server, but that might explain why the data isn't appearing. Anyway you can take a screenshot of the console errors you're receiving in your browser?

**Comment by willymaps** [comment]
Sounds like this was an issue with setting up a local server. Closing.
